package Client.GUI.Views;

import Client.GUI.GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LoginRegisterForm {
    private JPanel mainPane;
    private JButton submit;
    private JTextField passwordField;
    private JTextField usernameField;
    private JTextField privateKeyField;
    private JLabel username;
    private JLabel password;
    private JLabel key;
    private JLabel header;

    public LoginRegisterForm(GUI gui, boolean isLogin) {
        LoginRegisterForm t = this;
        this.header.setText(isLogin ? "Login" : "Register");
        submit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                String username = t.usernameField.getText();
                String password = t.passwordField.getText();
                String keyFileName = t.privateKeyField.getText();
                if (isLogin) {
                    gui.login(username, password, keyFileName);
                } else {
                    gui.register(username, password, keyFileName);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        submit = new JButton();
        submit.setText("Submit");
        mainPane.add(submit, BorderLayout.SOUTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPane.add(panel1, BorderLayout.CENTER);
        passwordField = new JTextField();
        passwordField.setPreferredSize(new Dimension(300, 30));
        panel1.add(passwordField, BorderLayout.CENTER);
        usernameField = new JTextField();
        usernameField.setPreferredSize(new Dimension(300, 30));
        panel1.add(usernameField, BorderLayout.NORTH);
        privateKeyField = new JTextField();
        privateKeyField.setPreferredSize(new Dimension(300, 30));
        privateKeyField.setText("");
        panel1.add(privateKeyField, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        mainPane.add(panel2, BorderLayout.WEST);
        username = new JLabel();
        username.setText("Username");
        panel2.add(username, BorderLayout.NORTH);
        password = new JLabel();
        password.setText("Password");
        panel2.add(password, BorderLayout.WEST);
        key = new JLabel();
        key.setText("Private key filename");
        panel2.add(key, BorderLayout.SOUTH);
        header = new JLabel();
        header.setHorizontalAlignment(0);
        header.setText("");
        mainPane.add(header, BorderLayout.NORTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

}
