package Client.GUI.Views;

import Client.GUI.GUI;
import Client.GUI.MessagesUpdater;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainForm extends JPanel implements MessagesUpdater {
    private JPanel mainPane;
    private JTextField usernameText;
    private JButton usernameButton;
    private JTextPane messages_list;
    private JTextField message;
    private JButton sendButton;


    public MainForm(GUI gui) {

        usernameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                gui.updateMessages(usernameText.getText());
            }
        });
        sendButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                gui.sendMessage(message.getText());
                message.setText("");
            }
        });
    }

    public void updateMessages(String messagesText) {
        this.messages_list.setText(messagesText);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPane.add(panel1, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Enter username to chat with:");
        panel1.add(label1, BorderLayout.WEST);
        usernameText = new JTextField();
        usernameText.setMinimumSize(new Dimension(300, 30));
        usernameText.setPreferredSize(new Dimension(300, 30));
        panel1.add(usernameText, BorderLayout.CENTER);
        usernameButton = new JButton();
        usernameButton.setText("Go to username");
        panel1.add(usernameButton, BorderLayout.EAST);
        messages_list = new JTextPane();
        messages_list.setEditable(false);
        messages_list.setMinimumSize(new Dimension(7, 400));
        messages_list.setPreferredSize(new Dimension(7, 400));
        mainPane.add(messages_list, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        mainPane.add(panel2, BorderLayout.SOUTH);
        message = new JTextField();
        panel2.add(message, BorderLayout.CENTER);
        sendButton = new JButton();
        sendButton.setText("Send");
        panel2.add(sendButton, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

}
